# Generated by Django 3.0.5 on 2022-10-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
